services:
  db:
    image: 'postgres:latest'
    restart: 'always'
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - '${PORT}:5432'
    volumes:
      - '${MIGRATION_PATH}:/docker-entrypoint-initdb.d/'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 15s
      retries: 3
